spring:
  profiles:
    active:
      dev: 
---
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-dev
---
spring:
  profiles: test
  application: 
    name: microservicecloud-config-test
# must be saved by UTF-8